# root-sync.yaml
apiVersion: configsync.gke.io/v1alpha1
kind: RootSync
metadata:
  name: root-sync
  namespace: config-management-system
spec:
  git:
    repo: https://github.com/willbeason/csmr-sample.git
    dir: "root-flat"
    auth: none
  sourceFormat: unstructured
